class Table{
  constructor(name, description, fields){
    this.name        = name; //string
    this.description = description; //string
    this.fields      = fields; //array of Fields
  }
}

class Field{
  constructor(name, definition, note, data_type){
    this.name       = name; //string
    this.definition = definition; //string
    this.note       = note; //string
    this.data_type  = data_type; //string
  }
}

/* table definitions (array) */
let table_definitions=[
  new Table("T_ReportPeriod",
    "Table specifies country, version of the reported data and reference year for reporting. Field repID is used in nearly all other tables for interlinking of these tables with table T_ReportPeriod. Field rptID is related to the table T_Reporter.",
    [
      new Field("repID",             "internal numerical database code (identification of country, reported period and data delivery version)", false, "Long integer"),
      new Field("rptID",             "internal numerical database code connecting data to proper reporter (link to the table T_Reporter)", false, "Long integer"),
      new Field("rptMStateKey",      "Member State abbreviation", "ISO 3166-alpha-2 code", "Text(2)"),
      new Field("repCode",           "Report ID", "All data are linked to Report ID defined in form Country and Contact Details", "Text(16)"),
      new Field("repVersion",        "Version of reported data", false, "Date(10)"),
      new Field("repSituationAt",    "Situation as at", "reference date", "Date(10)"),
      new Field("repReportedPeriod", "Reported Year", "reference year", "Text(4)"),
    ],
  ),

  new Table("T_Reporter",
    "Table provides information on reporting state.",
    [
      new Field("rptID",          "internal numerical database code (identification of the country and culture)", false, "Long integer"),
      new Field("rptMState",      "Specification of the country (link to the field lovID in the codelist table T_LOV)", "65 = Austria, 66 = Belgium, ..., 91 = Slovakia, 92 = United Kingdom, 132 = Croatia", "Integer"),
      new Field("rptMStateKey",   "Member State abbreviation", "ISO 3166-alpha-2 code", "Text(2)"),
      new Field("rptMStateValue", "Member State name", false, "Text(64)"),
      new Field("rptCulture",     "Culture code", false, "Text(5)"),
    ],
  ),

  new Table("T_ReceivingAreas",
    "Table summarises information on designated sensitive areas, date of designation, the purpose of the designation, type of sensitive areas. Moreover, the table specifies which particular article of the UWWTD is applied in regards to designation of sensitive areas. Field repID is related to the table T_ReportPeriod. Fields rcaState and rcaType are related to the field lovID in the codelist table T_LOV.",
    [
      new Field("rcaID",                 "internal numerical database code of Receiving area", false, "Long integer"),
      new Field("repID ",                "internal numerical database code connecting data to proper country, reported period and data delivery version (link to the table T_ReportPeriod)", false, "Long integer"),
      new Field("rptMStateKey",          "Member State abbreviation", "ISO 3166-alpha-2 code", "Text(2)"),
      new Field("rcaState",              "Status of the Receiving area (link to the field lovID in the codelist table T_LOV)", "105 = inactive, 106=active", "Integer"),
      new Field("rcaCode",               "ID of the Receiving area", false, "Text(32)"),
      new Field("rcaName",               "Name of the Receiving area", false, "Text(255)"),
      new Field("rcaType",               "Type of the Receiving area (link to the field lovID in the codelist table T_LOV)", "96 = application of Article 5(4), 97 = application of Article 5(8), 98 = catchment of sensitive area, 99 = less sensitive area, 100 = normal area, 101 = sensitive areas", "Integer"),
      new Field("rcaSensitiveArea",      "Related Sensitive area", "-999 = data not available", "Long integer"),
      new Field("rcaDateArt58",          "Starting date of application of Art. 5(8) of UWWTD", false, "Date"),
      new Field("rcaParameterN",         "Parameters subject to More Stringent Treatment: N", "0 = false, -1 = true", "Boolean"),
      new Field("rcaParameterP",         "Parameters subject to More Stringent Treatment: P", "0 = false, -1 = true", "Boolean"),
      new Field("rcaParameterOther",     "Parameters subject to More Stringent Treatment: Other", "0 = false, -1 = true", "Boolean"),
      new Field("rcaDateDesignation",    "Last date of designation or revision/ in case Art. 5(8) and 5(2-3) is applied: Starting date of application of Art. 5(2-3)", false, "Date"),
      new Field("rcaANitro",             "Designation Criteria (a, b, c): a - Nitrogen", "0 = false, -1 = true", "Boolean"),
      new Field("rcaAPhos",              "Designation Criteria (a, b, c): a - Phosphorus", "0 = false, -1 = true", "Boolean"),
      new Field("rcaB",                  "Designation Criteria (a, b, c): b", "0 = false, -1 = true", "Boolean"),
      new Field("rcaC",                  "Designation Criteria (a, b, c): c", "0 = false, -1 = true", "Boolean"),
      new Field("rcaCRelevantDirective", "Designation criteria c - relevant EU-Directives and related parameters", false, "Memo"),
      new Field("rcaMorphology",         "Less sensitive area - Designation criteria (Annex II B): Morphology", "0 = false, -1 = true", "Boolean"),
      new Field("rcaHydrologie",         "Less sensitive area - Designation criteria (Annex II B): Hydrology", "0 = false, -1 = true", "Boolean"),
      new Field("rcaHydraulic",          "Less sensitive area - Designation criteria (Annex II B): Specific hydraulic conditions", "0 = false, -1 = true", "Boolean"),
      new Field("rcaAbsenceRisk",        "Less sensitive area - Designation criteria (Annex II B): Absence of risk of transfer of discharged load to adjacent areas",  "0 = false, -1 = true", "Boolean"),
      new Field("rcaDateArt54",          "Starting date of application of Art. 5(4) of UWWTD", false, "Date"),
      new Field("rcaArt54Applied",       "Indication of application of Art. 5(4) of UWWTD", "0 = false, -1 = true", "Boolean"),
    ],
  ),

  new Table("T_Agglomerations",
    "Table contains information on agglomerations with generated load ≥ 2000 P.E., including names, coordinates, generated load and information whether the load generated is collected through collecting system or addressed via Individual Appropriate Systems (IAS) or not collected not addressed via IAS. Field repID is related to the table T_ReportPeriod. Field aggNUTS is related to the field nutID in the codelist table T_NUTS. Field bigID is related to the codelist table T_BigCity. Fields aggState, aggChanges, aggMethodC1, aggMethodC2 and aggMethodWithoutTreatment are related to the field lovID in the codelist table T_LOV.",
    [
      new Field("aggID",                     "internal numerical database code of Agglomeration", false, "Long integer"),
      new Field("aggState",                  "Status of the Agglomeration (link to the field lovID in the codelist table T_LOV)", "105 = inactive, 106 = active", "Integer"),
      new Field("repID",                     "internal numerical database code connecting data to proper country, reported period and data delivery version (link to the table T_ReportPeriod)", false, "Long integer"),
      new Field("rptMStateKey",              "Member State abbreviation", "ISO 3166-alpha-2 code", "Text(2)"),
      new Field("aggCode",                   "ID of the Agglomeration", false, "Text(32)"),
      new Field("aggName",                   "Name of the Agglomeration", false, "Text(255)"),
      new Field("aggNUTS",                   "internal numerical database code of Region (NUTS)) (link to the field nutID in the codelist table T_NUTS)", false, "Integer"),
      new Field("aggLatitude",               "Latitude (ETRS89, decimal degrees)", false, "Decimal"),
      new Field("aggLongitude",              "Longitude (ETRS89, decimal degrees)", false, "Decimal"),
      new Field("aggGenerated",              "Generated load (p.e.)", false, "Long integer"),
      new Field("bigID",                     "internal numerical database code of the Big city / Big discharger (link to the field bigID in the codelist table T_BigCity)", false, "Long integer"),
      new Field("aggCalculation",            "Methods used for calculation of the generated load of the agglomeration", false, "Memo"),
      new Field("aggChanges",                "Are there any significant changes of the generated load compared to the previous Report? (link to the field lovID in the codelist table T_LOV)", "122 = No, 123 = Yes", "Long integer"),
      new Field("aggChangesComment",         "Comments on significant changes of the generated load compared to the previous reported load", false, "Memo"),
      new Field("aggPeriodOver",             "Date of the relevant deadline of UWWTD or Transitional Period", false, "Date"),
      new Field("aggC1",                     "Rate of generated load of agglomeration collected through collecting system (% of p.e.)", false, "Decimal"),
      new Field("aggMethodC1",               "Method used to obtain the %-value (calculated or estimated, for aggC1) (link to the field lovID in the codelist table T_LOV)", "14 = calculated, 15 = estimated", "Integer"),
      new Field("aggC2",                     "Rate of generated load of agglomeration addressed through IAS (% of p.e.)", false, "Decimal"),
      new Field("aggMethodC2",               "Method used to obtain the %-value (calculated or estimated, for aggC2) (link to the field lovID in the codelist table T_LOV)", "14 = calculated, 15 = estimated", "Integer"),
      new Field("aggPercWithoutTreatment",   "Rate of generated load of agglomeration not collected through collecting systems and not addressed through IAS (% of p.e.)", false, "Decimal"),
      new Field("aggMethodWithoutTreatment", "Method used to obtain the %-value (calculated or estimated, for aggPercWithoutTreatment) (link to the field lovID in the codelist table T_LOV)", "0 = information not available, 14 = calculated, 15 = estimated", "Integer"),
    ],
  ),

  new Table("T_UWWTPS",
    "Table includes data on individual waste water treatment plants and collecting systems without UWWTP, their localisation, capacity and actual load treated, type of treatment, aggregated data on the performance of plants. Field repID is related to the table T_ReportPeriod. Field aggID is related to the table T_Agglomerations. Field uwwNUTS is related to the field nutID in the codelist table T_NUTS. Fields uwwState, uwwCollectingSystem, uwwBOD5Perf, uwwCODPerf, uwwTSSPerf, uwwNTotPerf, uwwPTotPerf and uwwOtherPerf are related to the field lovID in the codelist table T_LOV.",
    [
      new Field("uwwID",                 "internal numerical database code of UWWTP / collecting system without treatment", false, "Long integer"),
      new Field("uwwState",              "Status of the UWWTP (link to the field lovID in the codelist table T_LOV)", "105 = inactive, 106 = active", "Integer"),
      new Field("repID",                 "internal numerical database code connecting data to proper country, reported period and data delivery version (link to the table T_ReportPeriod)", false, "Long integer"),
      new Field("rptMStateKey",          "Member State abbreviation", "All data are linked to rpMStateKey; ISO 3166-alpha-2 code", "Text(2)"),
      new Field("aggID",                 "internal numerical database code of agglomeration (link to the table T_Agglomerations)", false, "Long integer"),
      new Field("uwwCode",               "ID of UWWTP / collecting system without treatment", false, "Text(32)"),
      new Field("uwwName",               "Name of UWWTP / collecting system without treatment", false, "Text(255)"),
      new Field("uwwCollectingSystem",   "Identification whether it is the existing UWWTP (in operation) or a collecting system without UWWTPs (link to the field lovID in the codelist table T_LOV)", "111 = collecting system connected to UWWTP, 112 = collecting system not connected to UWWTP", "Integer"),
      new Field("uwwDateClosing",        "Date of closing of the UWWTP", "year", "Integer"),
      new Field("uwwHistorie",           "Explanation for closing of the UWWTP / What happened with the wastewater since last reporting exercise", false, "Memo"),
      new Field("uwwLatitude",           "Latitude (ETRS89, decimal degrees)", false, "Decimal"),
      new Field("uwwLongitude",          "Longitude (ETRS89, decimal degrees)", false, "Decimal"),
      new Field("uwwNUTS",               "internal numerical database code of Region (NUTS) (link to the field nutID in the codelist table T_NUTS)", false, "Integer"),
      new Field("uwwLoadEnteringUWWTP",  "Load entering UWWTP (p.e.)", false, "Long integer"),
      new Field("uwwCapacity",           "Organic design capacity (p.e.)", false, "Long integer"),
      new Field("uwwPrimaryTreatment",   "Primary treatment", "0 = false, -1 = true", "Boolean"),
      new Field("uwwSecondaryTreatment", "Secondary treatment", "0 = false, -1 = true", "Boolean"),
      new Field("uwwOtherTreatment",     "More stringent treatment", "0 = false, -1 = true", "Boolean"),
      new Field("uwwNRemoval",           "N-removal", "0 = false, -1 = true", "Boolean"),
      new Field("uwwPRemoval",           "P-removal", "0 = false, -1 = true", "Boolean"),
      new Field("uwwUV",                 "UV", "0 = false, -1 = true", "Boolean"),
      new Field("uwwChlorination",       "Chlorination", "0 = false, -1 = true", "Boolean"),
      new Field("uwwOzonation",          "Ozonation", "0 = false, -1 = true", "Boolean"),
      new Field("uwwSandFiltration",     "Sand filtration", "0 = false, -1 = true", "Boolean"),
      new Field("uwwMicroFiltration",    "Micro filtration", "0 = false, -1 = true", "Boolean"),
      new Field("uwwOther",              "Other type of more stringent treatment", "0 = false, -1 = true", "Boolean"),
      new Field("uwwSpecification",      "Please specify other type of more stringent treatment", false, "Text(255)"),
      new Field("uwwBOD5Perf",           "Treatment performance: BOD5 (link to the field lovID in the codelist table T_LOV)", "0 = data not available, 1 = fail, 2 = pass, 94 = not relevant", "Integer"),
      new Field("uwwCODPerf",            "Treatment performance: COD (link to the field lovID in the codelist table T_LOV)", "0 = data not available, 93 = fail, 95 = pass, 94 = not relevant", "Integer"),
      new Field("uwwTSSPerf",            "Treatment performance: TSS (link to the field lovID in the codelist table T_LOV)", "93 = fail, 95 = pass, 94 = not relevant", "Integer"),
      new Field("uwwNTotPerf",           "Treatment performance: N (link to the field lovID in the codelist table T_LOV)", "93 = fail, 95 = pass, 94 = not relevant", "Integer"),
      new Field("uwwPTotPerf",           "Treatment performance: P (link to the field lovID in the codelist table T_LOV)", "93 = fail, 95 = pass, 94 = not relevant", "Integer"),
      new Field("uwwOtherPerf",          "Treatment performance: Other (link to the field lovID in the codelist table T_LOV)", "93 = fail, 95 = pass, 94 = not relevant", "Integer"),
    ],
  ),

  new Table("T_UWWTPAgglos",
    "Table is a connection table combining data on agglomeration and urban waste water treatment plants allowing repoting of situations where the ratio agglomeration:UWWTP is 1:n or m:1. Field repID is related to the table T_ReportPeriod. Field uwwID is related to the table T_UWWTPs. Fields aucUwwCode and aucUwwName are related to the fields uwwCode and uwwName in the table T_UWWTPs. Field aggID is related to the table T_Agglomerations. Fields aucAggCode and aucAggName are related to the fields aggCode and aggName in the table T_Agglomerations. Field aucMethodPercEnteringUWWTP is related to the field lovID in the codelist table T_LOV.",
    [
      new Field("aucID",                      "internal numerical database code of joint entry of agglomeration and UWWTP / collecting system without treatment", false,  "Long integer"),
      new Field("repID",                      "internal numerical database code connecting data to proper country, reported period and data delivery version (link to the table T_ReportPeriod)", false, "Long integer"),
      new Field("rptMStateKey",               "Member State abbreviation", "ISO 3166-alpha-2 code", "Text(2)"),
      new Field("uwwID",                      "internal numerical database code of UWWTP / collecting system without treatment (link to the table T_UWWTPs)", false, "Long integer"),
      new Field("aucUwwCode",                 "ID of UWWTP / collecting system without treatment (link to the field uwwCode in the table T_UWWTPs)", false, "Text(32)"),
      new Field("aucUwwName",                 "Name of the UWWTP (link to the field uwwName in the table T_UWWTPs)", false, "Text(255)"),
      new Field("aggID",                      "internal numerical database code of agglomeration entering that treatment plant (link to the tableT_Agglomerations)", false, "Long integer"),
      new Field("aucAggCode",                 "ID of the agglomeration entering that treatment plant (link to the field aggCode in the table T_Agglomerations)", false, "Text(32)"),
      new Field("aucAggName",                 "Name of the agglomeration entering that treatment plant (link to the field aggName in the table T_Agglomerations)", false, "Text(255)"),
      new Field("aucPercEnteringUWWTP",       "% of load of agglomeration collected in collecting system and entering that treatment plant", false, "Decimal"),
      new Field("aucMethodPercEnteringUWWTP", "Method used to obtain the % value (link to the field lovID in the codelist table T_LOV)", "14 = calculated, 15 = estimated", "Integer"),
      new Field("aucPercC2T",                 "Rate of generated load of agglomeration transported to this UWWTP by trucks (%)", false, "Decimal"),
    ],
  ),

  new Table("T_DischargePoints",
    "Table contains information on individual points of discharge from treatment plants or collecting systems, localisation of discharge, link to specific treatment plant, type of receiving area into which the effluent/wastewater is discharged, related waterbody (or river basin), information on the discharge on land. Field repID is related to the table T_ReportPeriod. Field uwwID is related to the table T_UWWTPs, to ensure the link between Discharge point and UWWTP. Field rcaID is related to the table T_ReceivingArea, to ensure the link between Discharge point and Receiving area, into which the treated waste water is discharged. Field dcpNUTS is related to the field nutID in the codelist table T_NUTS. Fields dcpState, dcpWaterBodyType, dcpTypeOfReceivingArea, dcpSurfaceWaters, dcpNotAffect, dcpMSProvide and dcpCOMAccept are related to the field lovID in the codelist table T_LOV.",
    [
      new Field("dcpID",                          "internal numerical database code of Discharge point", false, "Long integer"),
      new Field("dcpState",                       "Status of the Discharge point (link to the field lovID in the codelist table T_LOV)", "105 = inactive, 106 = active", "Integer"),
      new Field("repID",                          "internal numerical database code connecting data to proper country, reported period and data delivery version (link to the table T_ReportPeriod)", false, "Long integer"),
      new Field("rptMStateKey",                   "Member State abbreviation", "ISO 3166-alpha-2 code", "Text(2)"),
      new Field("uwwID",                          "internal numerical database code of UWWTP / collecting system without treatment (link to the table T_UWWTPs)", false, "Long integer"),
      new Field("dcpCode",                        "ID of the Discharge point", false, "Text(32)"),
      new Field("dcpName",                        "Name of the Discharge point", false, "Text(255)"),
      new Field("dcpNUTS",                        "internal numerical database code of Region (NUTS) (link to the field nutID in the codelist table T_NUTS)", false, "Long integer"),
      new Field("dcpLatitude",                    "Latitude (ETRS89, decimal degrees)", false, "Decimal"),
      new Field("dcpLongitude",                   "Longitude (ETRS89, decimal degrees)", false, "Decimal"),
      new Field("dcpWaterBodyType",               "Water body type (link to the field lovID in the codelist table T_LOV)", "113 and 118 = discharge in coastal water, 114 and 119 = discharge to estuary, 115 = discharge in freshwater, 116 and 120 = discharge on land catchment of fresh water, 117 and 121 = discharge on land catchment of coastal water", "Integer"),
      new Field("dcpIrrigation",                  "Purpose of discharge on land", false, "Integer"),
      new Field("dcpTypeOfReceivingArea",         "Type of Receiving area (link to the field lovID in the codelist table T_LOV)", "96 = application of Article 5(4), 97 = application of Article 5(8), 98 = catchment of sensitive area, 99 = less sensitive area, 100 = normal area, 101 = sensitive areas", "Integer"),
      new Field("rcaID",                          "internal numerical database code of Receiving area (link to the table T_ReceivingAreas)", "Relevant in case SA, CSA or LSA was chosen for parameter dcpTypeOfReceivingArea", "Long integer"),
      new Field("dcpSurfaceWaters",               "Availability of surface waters (link to the field lovID in the codelist table T_LOV)", "122 = no, 123 = yes", "Integer"),
      new Field("dcpWaterbodyID",                 "ID of WFD waterbody", false, "Text(64)"),
      new Field("dcpNotAffect",                   "Comprehensive studies indicate that the discharge does not adversely affect the environment (link to the field lovID in the codelist table T_LOV)", "122 = no, 123 = yes", "Integer"),
      new Field("dcpMSProvide",                   "Member State provided these studies to the Commission (link to the field lovID in the codelist table T_LOV)", "122 = no, 123 = yes", "Integer"),
      new Field("dcpCOMAccept",                   "Commission formally accept that the conditions under Art. 6(2) are met (link to the field lovID in the codelist table T_LOV)", "122 = no, 123 = yes", "Integer"),
      new Field("dcpGroundWater",                 "ID of WFD groundwater body", false, "Text(64)"),
      new Field("dcpReceivingWater",              "ID of receiving water", false, "Text(64)"),
      new Field("dcpWFDSubUnit",                  "ID of WFD sub-unit", false, "Text(64)"),
      new Field("dcpWFDRBD",                      "ID of WFD river basin district", false, "Text(64)"),
      new Field("dcpRemarks",                     "Remarks", false, "Memo"),
      new Field("dcpWFDRBDReferenceDate",         "Reference date of the WFD river basin district", false, "Date"),
      new Field("dcpWaterBodyReferenceDate",      "Reference date of the WFD waterbody", false, "Date"),
      new Field("dcpGroundWaterReferenceDate",    "Reference date of the WFD groundwater body", false, "Date"),
      new Field("dcpReceivingWaterReferenceDate", "Reference date of the receiving water", false, "Date"),
      new Field("dcpWFDSubUnitReferenceDate",     "Reference date of the WFD sub-unit", false, "Date"),
    ],
  ),

  new Table("T_MSLevel",
    "Table summarises aggregated (on MS level) information on the sludge handling, its discharge and/or disposal and re-use of treated water. Field mslMS is related to the field lovID in the codelist table T_LOV.",
    [
      new Field("mslID",                   "internal numerical database code", false, "Long integer"),
      new Field("mslMS",                   "Specification of the country (link to the field lovID in the codelist table T_LOV)", "65 = Austria, 66 = Belgium, ..., 91 = Slovakia, 92 = United Kingdom, 132 = Croatia", "Integer"),
      new Field("repID",                   "internal numerical database code connecting data to proper country, reported period and data delivery version (link to the table T_ReportPeriod)", false, "Long integer"),
      new Field("rptMStateKey",            "Member State abbreviation", "ISO 3166-alpha-2 code", "Text(2)"),
      new Field("mslSludgeProduction",     "Yearly production of sludge (t DS/y)", false, "Long integer"),
      new Field("mslDischargePipelines",   "Sludge discharged into surface waters: Pipelines (t DS/y)", false, "Decimal"),
      new Field("mslDischargeShips",       "Sludge discharged into surface waters: Ships (t DS/y)", false, "Decimal"),
      new Field("mslDischargeOthers",      "Sludge discharged into surface waters: Others (t DS/y)", false, "Decimal"),
      new Field("mslReuseSoilAgriculture", "Sludge re-used: Soil and agriculture (t DS/y)", false, "Decimal"),
      new Field("mslReuseOthers",          "Sludge re-used: Others (t DS/y)", false, "Decimal"),
      new Field("mslDisposalLandfill",     "Sludge disposed: Landfill (t DS/y)", false, "Decimal"),
      new Field("mslDisposalIncineration", "Sludge disposed: Incineration (t DS/y)", false, "Decimal (18)"),
      new Field("mslDisposalOthers",       "Sludge disposed: Others (t DS/y)", false, "Decimal"),
      new Field("mslRemarks",              "Remarks", false, "Text(255)"),
      new Field("mslWWReusePerc",          "Rate of treated waste water re-used (% of total volume treated)", false, "Integer"),
      new Field("mslWWReuseAgri",          "Re-use of treated waste water in: Agriculture", "0 = false, -1 = true", "Boolean"),
      new Field("mslWWReuseInd",           "Re-use of treated wastewater in: Industry", "0 = false, -1 = true", "Boolean"),
      new Field("mslWWReuseOther",         "Re-use of treated waste water in: Others", "0 = false, -1 = true", "Boolean"),
      new Field("mslWWReuseExplain",       "Re-use of treated waste water: Explanation of others", false, "Text(64)"),
    ],
  ),

  new Table("T_UWWTPS_emission_load",
    "Table contains additional data on incoming and discharged loads of organic matter and nutrients, provided by some Member States beyond the scope of UWWTD compliance. The data can be linked with the T_UWWTPs for further characteristics for the specific plants. A QA flag for some records relates to certain criteria and should be considered by the user for specific purposes. Field uwwState is related to the field lovID in the codelist table T_LOV. Fields uwwID, uwwCode and uwwName are related to the table T_UWWTPs.",
    [
      new Field("uwwState",     "Status of the UWWTP (link to the field lovID in the codelist table T_LOV)", "105 = inactive, 106 = active", "Integer"),
      new Field("rptMStateKey", "Member State abbreviation", "ISO 3166-alpha-2 code", "Text(2)"),
      new Field("uwwID",        "internal numerical database code of UWWTP / collecting system without treatment (link to the table T_UWWTPs)", false, "Long integer"),
      new Field("uwwCode",      "ID of UWWTP / collecting system without treatment (link to the field uwwCode in the table T_UWWTPs)", false, "Text(32)"),
      new Field("uwwName",      "Name of the UWWTP (link to the field uwwName in the table T_UWWTPs)", false, "Text(255)"),
      new Field("BODIncoming",  "Incoming loads (t/y): BOD", false, "Decimal"),
      new Field("CODIncoming",  "Incoming loads (t/y): COD", false, "Decimal"),
      new Field("NIncoming",    "Incoming loads (t/y): Ntot", false, "Decimal"),
      new Field("PIncoming",    "Incoming loads (t/y): Ptot", false, "Decimal"),
      new Field("BODDischarge", "Discharged loads (t/y): BOD", false, "Decimal"),
      new Field("CODDischarge", "Discharged loads (t/y): COD", false, "Decimal"),
      new Field("NDischarge",   "Discharged loads (t/y): Ntot", false, "Decimal"),
      new Field("PDischarge",   "Discharged loads (t/y): Ptot", false, "Decimal"),
      new Field("QA flag",      "information on the data flagging", "Y = record flagged", "Text(1)"),
      new Field("Remark",       "reference to the detailed information on the QA of the emission load data", false, "Text(255)"),
    ],
  ),

  new Table("T_Add_on_Agglomerations",
    "Table provides additional information on population connected to Individual Appropriate System (IAS) and population not connected to any type of treatment nor collecting system without treatment. The data is provided at agglomeration level and is supplementary to data reported in Table Agglomerations.",
    [
      new Field("aggID",                          "internal numerical database code of Agglomeration (can't be used as link to the table T_Agglomerations)", false, "Long integer"),
      new Field("aggState",                       "Status of the Agglomeration (link to the field lovID in the codelist table T_LOV)", "105 = inactive, 106 = active", "Integer"),
      new Field("repID",                          "internal numerical database code connecting data to proper country, reported period and data delivery version (link to the table T_ReportPeriod)", false, "Long integer"),
      new Field("aggCode",                        "ID of the Agglomeration (link to the table T_Agglomerations)", false, "Text(32)"),
      new Field("aggName",                        "Name of the Agglomeration (link to the table T_Agglomerations)", false, "Text(255)"),
      new Field("aggInhabitantsConnectedIAS",     "number of inhabitants connected to Individual Appropriate Systems of waste water treatment", false, "Long integer"),
      new Field("aggInhabitantsWithoutTreatment", "number of inhabitants not to collecting systems nor to Individual Appropriate Systems of waste water treatment", false, "Long integer"),
      new Field("aggRemarks",                     "Memo    Text(255)"),
    ],
  ),

  new Table("T_Add_on_UWWTPs",
    "The data provided in this table is supplementary to information reported in Table UWWTPS. The table contains Information on population connected to individual waste water treatment plant or collecting system, EPRTR code of facility (waste water treatment plants) if relevant, information whether more stringent effluent standards apply to the individual waste water treatment plant. Moreover, Member States can provide information on the type of effluent flow.",
    [
      new Field("uwwID",                          "internal numerical database code of UWWTP / collecting system without treatment (can't be used as link to the table T_UWWTPs)", false, "Long integer"),
      new Field("uwwState",                       "Status of the UWWTP (link to the field lovID in the codelist table T_LOV)", "105 = inactive, 106 = active", "Integer"),
      new Field("repID",                          "internal numerical database code connecting data to proper country, reported period and data delivery version (link to the table T_ReportPeriod)", false, "Long integer"),
      new Field("uwwCode",                        "ID of UWWTP / collecting system without treatment (link to the table T_UWWTPs)", false, "Text(32)"),
      new Field("uwwName",                        "Name of UWWTP / collecting system without treatment (link to the table T_UWWTPs)", false, "Text(255)"),
      new Field("uwwCollectingSystem",            "Identification whether it is the existing UWWTP (in operation) or a collecting system without UWWTPs (link to the field lovID in the codelist table T_LOV)", "111 = collecting system connected to UWWTP, 112 = collecting system not connected to UWWTP", "Integer"),
      new Field("uwwE_PRTRCode",                  "E-PRTR code of waste water treatment plant under which it is reported in E-PRTR database", false, "Text(128)"),
      new Field("uwwpInhabitantsConnected",       "number of inhabitants connected to waste water treatment plant", false, "Long integer"),
      new Field("uwwMoreStringentStandards",      "Indication of application of more stringent effluent standards as compared to UWWTD", false, "Boolean"),
      new Field("uwwMoreStringentStandardsNtot",  "Indication of application of more stringent effluent standards for N total as compared to UWWTD", false, "Boolean"),
      new Field("uwwMoreStringentStandardsPtot",  "Indication of application of more stringent effluent standards for Ptotal as compared to UWWTD", false, "Boolean"),
      new Field("uwwMoreStringentStandardsBOD",   "Indication of application of more stringent effluent standards for BOD as compared to UWWTD", false, "Boolean"),
      new Field("uwwMoreStringentStandardsOther", "Indication of application of more stringent effluent standards for other parameters as compared to UWWTD", false, "Text(255)"),
      new Field("uwwEffluentFLowType",            "Specification of effluent treatment", "1-fully treated effluent- dry and wet weather, partially treated storm water; 2-fully treated effluent- dry and wet weather; 3-fully treated effluent- dry weather;", "Integer"),
      new Field("uwwEffluentFLowTypeRemark",      "Remarks on the CSO", false, "Text(255)"),
      new Field("uwwRemarks",                     "Memo", false, "Text(255)"),
    ],
  ),

  new Table("T_Add_on_MSLevel",
    "Table contains aggregated information (at MS level) on population connected to collecting systems, wastewater treatment plants, population not connected to any type of treatment. The data is provided for both agglomeration above and below 2000 p.e.",
    [
      new Field("repID",                                "internal numerical database code connecting data to proper country, reported period and data delivery version (link to the table T_ReportPeriod)", false, "Long integer"),
      new Field("mslInhabitantsConnetecIAS",            "Number of inhabitants connected to IAS", false, "Long integer"),
      new Field("mslInhabitantsWithoutTreatment",       "Number of inhabitants not connected to collecting system nor served by IAS", false, "Long integer"),
      new Field("mslInhabitantsUwwtpCollsys",           "Number of inhabitants connected to collecting system or treatment plant", false, "Long integer"),
      new Field("mslInhabitantsUwwtpAgglo2",            "Number of inhabitants connected to collecting system or treatment plant serving agglomeration smaller than 2 000 p.e.", false, "Long integer"),
      new Field("mslInhabitantsIASAgglo2",              "Number of inhabitants connected to collecting system or treatment plant serving agglomeration smaller than 2 000 p.e.", false, "Long integer"),
      new Field("mslInhabitantsWithoutTreatmentAgglo2", "Number of inhabitants in agglomeration smaller than 2 000 p.e.", false, "Long integer"),
      new Field("mslInfoFateWithoutTreatment",          "brief text information on the fate of generated wastewater", false, "Text(255)"),
    ],
  ),

  new Table("T_BigCity",
    "Codelist of Big cities / Big discharges",
    [
      new Field("bigID", "internal numerical database code of the Big city", false, "Long integer"),
      new Field("bigCityID", "ID of the Big city", false, "Text(32)"),
      new Field("bigCountryCode", "Member State abbreviation", "ISO 3166-alpha-2 code", "Text(4)"),
      new Field("bigCity", "Name of the BigCity", "Text(255)"),
    ],
  ),

  new Table("T_NUTS",
    "Codelist of NUTS",
    [
      new Field("nutID", "internal numerical database code of the NUTS", false, "Long integer"),
      new Field("nutNUTS", "ID of the NUTS", false, "Text(16)"),
      new Field("nutCountryCode", "Member State abbreviation", "ISO 3166-alpha-2 code", "Text(2)"),
      new Field("nutRegion", "Name of the NUTS", false, "Text(64)"),
    ],
  ),

  new Table("T_LOV",
    "Common codelist of values appropriated to various fields and tables",
    [
      new Field("lovID", "internal numerical database code of the LOV", false, "Long integer"),
      new Field("lovName", "Name of the LOV", false, "Text(32)"),
      new Field("lovKey", "Key of the LOV", false, "Text(16)"),
      new Field("lovValue", "Value of the LOV", false, "Text(64)"),
    ]
  ),
];
