INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("AT006","GRAZ","AT","Austria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("AT007","INNSBRUCK","AT","Austria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("AT014","LINZ","AT","Austria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("AT016","SALZBURG","AT","Austria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("AT022","WIEN","AT","Austria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ATAG_2-K1931629","Klagenfurt (Worthersee Ost)","AT","Austria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ATAG_2-K1939997","Villach","AT","Austria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ATAG_3-11","Raum Schwechat (Schwechat-Mannsworth)","AT","Austria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ATAG_3-119","Raum Krems (Krems-Weinzierl)","AT","Austria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ATAG_3-449","Raum Wiener Neustadt (Wiener Neustadt-Lichtenworth)","AT","Austria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ATAG_3-47","Raum St. Polten (Traismauer-Stollhofen)","AT","Austria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ATAG_4-41812001","Wels und Umgebung","AT","Austria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ATAG_7-7930111","Strass/Zillertal (Achental-Inntal-Zillertal)","AT","Austria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ATAG_8-Hofsteig","Hard (Region Hofsteig)","AT","Austria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ATAG_8-Hohenems","Hohenems (Region Hohenems)","AT","Austria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ATAG_8-Meiningen","Meiningen (Region Feldkirch)","AT","Austria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("BE004","ANTWERPEN","BE","Belgium");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("BE013","BRUGGE","BE","Belgium");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("BE014","BRUXELLES/BRUSSEL","BE","Belgium");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("BE015","CHARLEROI","BE","Belgium");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("BE022","GENT","BE","Belgium");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("BE034","LIEGE","BE","Belgium");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("BE044","MONS","BE","Belgium");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("BE2","OOSTENDE","BE","Belgium");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("BE310","WAVRE","BE","Belgium");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("BE324","MOUSCRON","BE","Belgium");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("BE325","LA LOUVIERE","BE","Belgium");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("BG003","BURGAS","BG","Bulgaria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("BG013","PLEVEN","BG","Bulgaria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("BG014","PLOVDIV","BG","Bulgaria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("BG016","RUSE","BG","Bulgaria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("BG019","SLIVEN","BG","Bulgaria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("BG020","SOFIYA","BG","Bulgaria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("BG021","STARA ZAGORA","BG","Bulgaria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("BG022","DOBRICH","BG","Bulgaria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("BG023","VARNA","BG","Bulgaria");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("CH_CITY_0230","Winterthur","CH","Switzerland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("CH_CITY_0261","Zürich","CH","Switzerland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("CH_CITY_0351","Bern","CH","Switzerland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("CH_CITY_2701","Basel","CH","Switzerland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("CH_CITY_5586","Lausanne","CH","Switzerland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("CH_CITY_6621","Geneve","CH","Switzerland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("CY001","NICOSIA","CY","Cyprus");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("CY005","LIMASSOL","CY","Cyprus");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("CZ003","BRNO","CZ","Czechia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("CZ015","HRADEC KRALOVE","CZ","Czechia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("CZ029","LIBEREC","CZ","Czechia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("CZ039","OLOMOUC","CZ","Czechia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("CZ042","OSTRAVA","CZ","Czechia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("CZ046","PLZEN","CZ","Czechia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("CZ047","PRAHA","CZ","Czechia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE001","AACHEN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE025","AUGSBURG","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE055","BERGISCH GLADBACH","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE057","BERLIN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE059","BIELEFELD","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE067","BOCHUM","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE068","BONN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE072","BOTTROP","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE076","BRAUNSCHWEIG","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE077","BREMEN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE078","BREMERHAVEN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE093","CHEMNITZ","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE098","COTTBUS","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE103","DARMSTADT","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE109","DESSAU","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE119","DORTMUND","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE121","DRESDEN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE123","DUISBURG","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE126","DUESSELDORF","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE144","ERFURT","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE147","ERLANGEN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE151","ESSEN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE163","FRANKFURT AM MAIN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE167","FREIBURG IM BREISGAU","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE187","GELSENKIRCHEN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE189","GERA","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE204","GOETTINGEN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE216","HAGEN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE219","HALLE","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE221","HAMBURG","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE223","HAMM","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE226","HANNOVER","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE230","HEIDELBERG","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE233","HEILBRONN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE244","HERNE","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE250","HILDESHEIM","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE267","JENA","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE274","KARLSRUHE","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE275","KASSEL","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE283","KIEL","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE287","KOBLENZ","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE288","KOELN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE295","KREFELD","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE314","LEIPZIG","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE319","LEVERKUSEN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE331","LUEBECK","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE336","LUDWIGSHAFEN AM RHEIN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE339","MAGDEBURG","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE341","MAINZ","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE342","MANNHEIM","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE361","MOERS","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE362","MONCHEN-GLADBACH","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE369","MUELHEIM AN DER RUHR","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE370","MUENCHEN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE372","MUENSTER","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE387","NEUSS","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE400","NURNBERG","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE402","OBERHAUSEN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE407","OFFENBACH AM MAIN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE409","OLDENBURG","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE412","OSNABRUECK","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE417","PADERBORN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE423","PFORZHEIM","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE431","POTSDAM","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE443","RECKLINGHAUSEN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE444","REGENSBURG","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE447","REMSCHEID","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE461","ROSTOCK","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE468","SAARBRUECKEN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE470","SALZGITTER","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE490","SCHWERIN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE498","SIEGEN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE503","SOLINGEN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE526","STUTTGART","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE538","ULM","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE583","WIESBADEN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE591","WITTEN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE596","WOLFSBURG","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE600","WUPPERTAL","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE602","WUERZBURG","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DE607","ZWICKAU","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_BW1155100000016","Boblingen-Sindelfingen/KW 1","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_BW1175100000062","Goppingen","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_BW2165100000007","Buhl und Umgebung	Vimbuch","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_BW2265100000005","Bergstrasse	Weinheim","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_BW2265100000007","Schwetzingen-Ketsch","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_BW3355100000005","Konstanz","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_BW3365100000001","Wieseverband	Weil am Rhein-Bandlegrund","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_BW4165100000066","Tubingen","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_BW4365100000025","Mariatal	Ravensburg-Eschach-Langwiese","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_BYAB-K0022","Gemeinschaftsklaranlage Bayer. Untermain GmbH","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_BYHO-K0002","ZV Sachsische Saale","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_BYHO-K0089","Bayreuth","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_BYHO-K0180","Kulmbach","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_BYIN-K0003","ZV ZENTRALKLAERANLAGE INGOLSTADT","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_BYKC-K0001","BAMBERG","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_BYKE-K0020","ZV GRUPPENKLAERWERK KEMPTEN S. LAUBEN","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_BYKG-K0001","Schweinfurt","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_BYM-K0121","AmperVerband","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_BYN-K0003","FUERTH","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_BYRO-K0001","ROSENHEIM","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_HE064350140131","Hanau / Nordwest","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_HE065310050471","Giessen / Margaretenhutte/Sudliche Lahns","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_HE065340143511","Marburg / Cappel","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_HE066310091101","Fulda / Glaserzell","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_MV06.06.1 wbu1533","Wismar","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_MV52.74.3 wbu2539","Stavenhagen","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_NI252006201","Hameln","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_NI255023201","Holzminden","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_NI352011201","Cuxhaven","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_NI355022201","Luneburg","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_NI454032201","Lingen","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_NI456015201","Nordhorn","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_NW1913","Stadt Sankt Augustin","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_NW2516","Stadt Lunen","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_NW2529","Stadt Kamen","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_NW2782","Stadt Minden","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_NW2797","Stadt Herford","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_NW3013","Stadt Coesfeld","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_NW3061","Stadt Rheine","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_NW316","Stadt Gutersloh","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_NW329","Stadt Rheda-Wiedenbruck","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_NW35","Stadt Duren","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_NW905","Stadt Dinslaken","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_RP100601008","Kaiserslautern","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_RP102430091","Worms","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_SH56027","AZV Pinneberg","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_SH58044","Neumunster","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DEAG_ST151541000001","Bitterfeld	 Wolfen","DE","Germany");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DK001","AALBORG","DK","Denmark");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DK013","KOEBENHAVN","DK","Denmark");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DK017","ODENSE","DK","Denmark");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DK026","AARHUS","DK","Denmark");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DK278","ESBJERG","DK","Denmark");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DK367","FREDERICIA CENTRALRENS","DK","Denmark");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DK378","HOLSTEBRO","DK","Denmark");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DK400","?BY","DK","Denmark");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DK429","SKAGEN","DK","Denmark");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DK434","RANDERS","DK","Denmark");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DK437","HERNING","DK","Denmark");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("DK455","HORSENS","DK","Denmark");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("EE002","TALLINN","EE","Estonia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("EE003","TARTU","EE","Estonia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("EEIV0044","Kohtla-Jarve","EE","Estonia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES003","ALBACETE","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES005","ALCALA DE HENARES","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES014","ALGECIRAS","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES016","ALICANTE","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES019","ALMERIA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES030","BADAJOZ","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES033","BARCELONA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES037","BILBAO","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES039","BURGOS","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES042","CADIZ","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES052","CASTELLON DE LA PLANA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES059","CORDOBA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES068","DONOSTIA-SAN SEBASTIAN","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES075","ELCHE","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES081","FUENLABRADA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES086","GIJON","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES087","GRANADA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES092","HUELVA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES099","JAEN","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES100","JEREZ DE LA FRONTERA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES10030310001022","BENIDORM	 FINESTRAT	 L'ALFAS DEL PI	 LA NUCIA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES10030660001010","ELDA	 MONOVER	 PETRER	 SAX","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES10031330002060","TORREVIEJA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES102","LA CORUNA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES10461100001010","ALAQUAS	 ALDAIA	 MANISES	 MISLATA	 QUART DE POBLET	 VALENCIA	 XIRIVELLA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES10461310002010","RJO	 BENIFLA	 BENIRREDRA 	 DAIMUS	 GANDIA	 GUARDAMAR DE LA SAFOR	 L'ALQUERIA DE LA COMTESSA	 LA FONT D'EN CARROS	 MIRAMAR	 PALMERA	 PILES	 POTRIES	 RAFELCOFER	 REAL DE GANDIA	 VILLALONGA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES10461990001010","ALBUIXECH	 EMPERADOR	 LA POBLA DE FARNALS	 MASSALFASSAR	 MASSAMAGRELL	 MUSEROS	 PUZOL	 PUIG	 RAFELBUNYOL","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES108","LAS PALMAS DE GRAN CANARIA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES110","LEON","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES111","LERIDA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES114","LOGRONO","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES119","MADRID","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES121","MALAGA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES12150782911010","SANTIAGO","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES127","MATARO","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES1290670005020","PEÑON DEL CUERVO","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES1290690015010","ARROYO DE LA VIBORA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES13280130002010","ARANJUEZ","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES13280140001010","ARGANDA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES13280470001010","COLLADO VILLALBA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES13280960003010","NAVALCARNERO","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES13281300002010","SAN FERNANDO DE HENARES","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES13281480001010","TORREJÓN DE ARDOZ","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES139","MURCIA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES1410700001010","ALJARAFE II","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES14300160001030","CARTAGENA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES14300161912010","MAR MENOR SUR","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES14300270011011","MOLINA DE SEGURA NORTE","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES146","OVIEDO","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES148","PALMA DE MALLORCA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES149","PAMPLONA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES169","SABADELL","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES171","SALAMANCA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES181","SANTA CRUZ DE TENERIFE","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES183","SANTANDER","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES18510010000000","CEUTA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES188","SEVILLA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES194","TERRASA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES206","VALENCIA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES208","VALLADOLID","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES211","VIGO","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES220","VITORIA-GASTEIZ","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES225","ZARAGOZA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES232","ALCORCON","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES259","BADALONA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES306","MONTCADA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES332","GETAFE","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES3330040101010","AVILES","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES3330441901011","NORA-NOREA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES335","HOSPITALET DE LLOBREGAT (L')","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES345","LEGANES","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES374","MOSTOLES","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES424","SAN VICENTE DE BARAKALDO","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES436","SANTA COLOMA DE GRAMENET","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES5380010800010","ADEJE-ARONA OESTE (ADEJE	ARONA)","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES6390850005010","VUELTA OSTRERA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES7050190003010","AVILA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES7341200001010","PALENCIA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES8130050002010","ALCAZAR DE SAN JUAN- CAMPO DE CRIPTANA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES8130340002010","CIUDAD REAL-MIGUELTURRA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES8451650006010","TALAVERA DE LA REINA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES9080960001010","GRANOLLERS","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES9081050001010","LLAGOSTA	 LA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES9081360001010","MONTORNES DEL VALLES","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES9081630001040","PINEDA DE MAR","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES9081690001010","PRAT DE LLOBREGAT (EL)","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES9081840001010","RUBI","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES9082110001010","SANT FELIU DE LLOBREGAT","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES9082980001010","VIC","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES9083010001010","GAVA-VILADECANS","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES9170790005010","GIRONA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("ES9431480013010","TARRAGONA","ES","Spain");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FI003","HELSINKI","FI","Finland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FI019","LAHTI","FI","Finland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FI023","OULU","FI","Finland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FI034","TAMPERE","FI","Finland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FI036","TURKU","FI","Finland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FIYKR05_T001477","Pori","FI","Finland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR009","AMIENS","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR010","ANGERS","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR010000159220","FACHES-THUMESNIL","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR010000159512","ROUBAIX","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR010000162041","ARRAS","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR010000162160","BOULOGNE-SUR-MER","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR010000162351","FOUQUIERES-LES-LENS","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR011","ANGOULEME","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR012","ANNECY","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR020000168066","COLMAR","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR024","AVIGNON","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR028","BIARRITZ","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR030000177243","LAGNY-SUR-MARNE","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR030000177284","MEAUX","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR030000178646","VERSAILLES","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR030000191228","EVRY","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR030000195127","CERGY-PONTOISE","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR030000195585","SARCELLES","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR033","BESANCON","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR034","BETHUNE","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR037","BORDEAUX","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR040000129232","QUIMPER","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR040000153130","LAVAL","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR042","BREST","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR045","CAEN","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR047","CALAIS","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR050000112202","RODEZ","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR050000119031","BRIVE-LA-GAILLARDE","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR056","CHAMBERY","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR060000171270","MACON","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR060000183061","FREJUS","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR064","CLERMONT-FERRAND","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR074","DIJON","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR076","DOUAI","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR079","COUDEKERQUE-BRANCHE","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR095","CANNES-GRASSE-ANTIBES","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR096","GRENOBLE","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR098","HAGONDANGE","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR100000197414","SAINT-LOUIS","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR107","ROCHELLE","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR112","HAVRE","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR113","LE MANS","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR115","LENS","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR118","LILLE","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR119","LIMOGES","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR122","LORIENT","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR124","LYON","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR128","MARSEILLE-AIX-EN-PROVENCE","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR130","MAUBEUGE","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR132","MELUN","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR134","METZ","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR140","MONTBELIARD","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR145","MONTPELLIER","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR147","MULHOUSE","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR148","NANCY","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR149","NANTES","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR152","NICE","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR153","NIMES","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR156","ORLEANS","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR159","PARIS","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR160","PAU","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR162","PERPIGNAN","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR165","POITIERS","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR170","REIMS","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR171","RENNES","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR176","ROUEN","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR181","SAINT ETIENNE","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR184","SAINT NAZAIRE","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR197","STRASBOURG","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR199","THIONVILLE","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR201","TOULON","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR202","TOULOUSE","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR203","TOURS","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR205","TROYES","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR208","VALENCE","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("FR209","VALENCIENNES","FR","France");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("GR005","ATHINAI","GR","Greece");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("GR010","IRAKLION","GR","Greece");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("GR023","LARISA","GR","Greece");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("GR025","PATRAI","GR","Greece");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("GR031","THESSALONIKI","GR","Greece");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("GR035","VOLOS","GR","Greece");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("HRBC_0001116","Rijeka","HR","Croatia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("HRBC_0001131","Split-Solin","HR","Croatia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("HRBC_0004008","Zagreb","HR","Croatia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("HRBC_0007012","Osijek","HR","Croatia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("HU006","BUDAPEST","HU","Hungary");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("HU009","DEBRECEN","HU","Hungary");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("HU018","GYOR","HU","Hungary");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("HU038","MISKOLC","HU","Hungary");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("HU049","PECS","HU","Hungary");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("HU054","SZEGED","HU","Hungary");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("HU055","SZEKESFEHERVAR","HU","Hungary");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("HU062","Kecskemet - Szennyvizelvezetesi Agglomeracio","HU","Hungary");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("HU064","Nyiregyhaza - Szennyvizelvezetesi Agglomeracio","HU","Hungary");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("HU065","Szombathely - Szennyvizelvezetesi Agglomeracio","HU","Hungary");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IE002","CORK","IE","Ireland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IE006","DUBLIN","IE","Ireland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IE010","Dundalk","IE","Ireland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IE011","Killybegs","IE","Ireland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IS001","REYKJAVIK","IS","Iceland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT009","CERVIA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT019","ANCONA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT035","AVERSA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT042","BARI","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT048","BERGAMO","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT054","BOLOGNA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT058","BRESCIA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT063","CAGLIARI","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT084","CASERTA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT093","CATANIA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT123","COMO","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT131","COSENZA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT152","FERRARA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT154","FIRENZE","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT155","FOGGIA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT170","GALLARATE","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT174","GENOVA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT200","LA SPEZIA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT213","LIVORNO","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT215","LUCCA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT231","MASSA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT239","MESSINA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT240","MILANO","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT246","MODENA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT267","NAPOLI","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT270","FORLÌ","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT293","PADOVA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT295","PALERMO","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT298","PARMA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT302","PERUGIA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT304","PESCARA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT311","PISA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT312","PISTOIA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT327","PRATO","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT335","REGGIO DI CALABRIA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT336","REGGIO NELL'EMILIA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT342","RIMINI","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT344","ROMA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT353","SALERNO","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT395","SIRACUSA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT402","TARANTO","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT410","TORINO","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT419","TREVISO","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT421","TRIESTE","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT423","UDINE","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT426","VARESE","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT434","VERONA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT437","VICENZA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT737","MESTRE","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT789","COMACCHIO","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT945","RAVENNA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("IT946","PIACENZA","IT","Italy");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("LT002","KAUNAS","LT","Lithuania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("LT003","KLAIPEDA","LT","Lithuania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("LT004","PANEVEZYS","LT","Lithuania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("LT005","SIAULIAI","LT","Lithuania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("LT006","VILNIUS","LT","Lithuania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("LU002","LUXEMBOURG","LU","Luxembourg");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("LV001","DAUGAVPILS","LV","Latvia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("LV003","LIEPAJA","LV","Latvia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("LV004","RIGA","LV","Latvia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("MT001","VALLETTA","MT","Malta");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NLBG01033","GRONINGEN","NL","Netherlands");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NLBG05013","ENSCHEDE","NL","Netherlands");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NLBG05017","HENGELO","NL","Netherlands");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NLBG07020","ARNHEM","NL","Netherlands");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NLBG08011","HARDERWIJK","NL","Netherlands");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NLBG09024","NIJMEGEN","NL","Netherlands");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NLBG10009","UTRECHT","NL","Netherlands");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NLBG10027","AMERSFOORT","NL","Netherlands");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NLBG12004","BEVERWIJK","NL","Netherlands");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NLBG15005","'S-GRAVENHAGE","NL","Netherlands");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NLBG17061","ROTTERDAM","NL","Netherlands");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NLBG25017","BREDA","NL","Netherlands");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NLBG25021","BERGEN OP ZOOM","NL","Netherlands");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NLBG27003","EINDHOVEN","NL","Netherlands");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NLBG27008","'S HERTOGENBOSCH","NL","Netherlands");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NLBG28003","HELMOND","NL","Netherlands");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NLBG28005","VEGHEL","NL","Netherlands");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NLBG29002","OSS","NL","Netherlands");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NLBG30015","HEERLEN","NL","Netherlands");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NLBG30017","VENLO","NL","Netherlands");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NLBG31003","AMSTERDAM","NL","Netherlands");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NLBG32001","TILBURG","NL","Netherlands");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NO003","BERGEN","NO","Norway");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NO017","OSLO","NO","Norway");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NO025","STAVANGER","NO","Norway");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("NO029","TRONDHEIM","NO","Norway");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL008","BIALYSTOK","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL010","BIELSKO-BIALA","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL017","BYDGOSZCZ","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL018","BYTOM","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL023","CHORZOW","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL027","CZESTOCHOWA","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL028","DABROWA GORNICZA","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL032","ELBLAG","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL034","GDANSK","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL035","GDYNIA","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL037","GLIWICE","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL042","GORZOWWIELKOPOLSKI","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL047","GRUDZIADZ","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL059","KALISZ","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL061","KATOWICE","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL064","KIELCE","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL073","KOSZALIN","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL074","KRAKOW","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL084","LEGNICA","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL086","LODZ","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL093","LUBLIN","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL113","OLSZTYN","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL115","OPOLE","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL128","PLOCK","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL130","POZNAN","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL138","RADOM","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL141","RYBNIK","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL142","RZESZOW","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL150","SLUPSK","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL153","SOSNOWIEC","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL167","SZCZECIN","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL171","TARNOW","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL176","TORUN","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL179","TYCHY","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL181","WALBRZYCH","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL183","WARSZAWA","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL186","WLOCLAWEK","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL189","WROCLAW","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL192","ZABRZE","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL201","ZIELONA GORA","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL206","RUDA SLASKA","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PL207","JASTRZEBIE-ZDROJ","PL","Poland");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PT004","AMADORA","PT","Portugal");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PT018","LISBOA","PT","Portugal");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PT022","PORTO","PT","Portugal");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PTAGL016","Barreiro/Moita","PT","Portugal");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PTAGL048","Coimbra","PT","Portugal");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PTAGL049","Costa de Aveiro","PT","Portugal");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PTAGL060","Alcanena","PT","Portugal");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PTAGL070","Costa do Estoril","PT","Portugal");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PTAGL085","Setubal","PT","Portugal");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PTAGL105","Matosinhos","PT","Portugal");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PTAGL116","Santo Tirso","PT","Portugal");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PTAGL117","Gaia/Litoral","PT","Portugal");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PTAGL131","Loures/Frielas","PT","Portugal");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("PTAGL306","Famalicao/Sto Tirso/Trofa","PT","Portugal");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("RO005","ARAD","RO","Romania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("RO006","BACAU","RO","Romania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("RO007","BAIA MARE","RO","Romania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("RO016","BOTOSANI","RO","Romania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("RO018","BRAILA","RO","Romania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("RO019","BRASOV","RO","Romania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("RO020","BUCURESTI","RO","Romania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("RO022","BUZAU","RO","Romania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("RO033","CLUJ-NAPOCA","RO","Romania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("RO036","CONSTANTA","RO","Romania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("RO038","CRAIOVA","RO","Romania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("RO049","GALATI","RO","Romania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("RO056","IASI","RO","Romania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("RO070","ORADEA","RO","Romania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("RO075","PIATRA NEAMT","RO","Romania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("RO076","PITESTI","RO","Romania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("RO077","PLOIESTI","RO","Romania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("RO082","RIMNICU VILCEA","RO","Romania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("RO087","SATU MARE","RO","Romania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("RO090","SIBIU","RO","Romania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("RO094","SUCEAVA","RO","Romania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("RO096","TIMISOARA","RO","Romania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("RO100","TIRGU MURES","RO","Romania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("RO112","DROBETA-TURNU SEVERIN","RO","Romania");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("SE008","GOETEBORG","SE","Sweden");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("SE026","MALMOE","SE","Sweden");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("SE036","STOCKHOLM","SE","Sweden");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("SE044","UPPSALA","SE","Sweden");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("SE054","VAESTERAAS","SE","Sweden");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("SE_AGGLO_1004","HELSINGBORG","SE","Sweden");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("SE_AGGLO_1005","LINKOEPING","SE","Sweden");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("SI009","LJUBLJANA","SI","Slovenia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("SI010","MARIBOR","SI","Slovenia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("SK002","NITRA","SK","Slovakia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("SK004","BRATISLAVA","SK","Slovakia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("SK006","LIPTOVSKY MIKULAS","SK","Slovakia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("SK008","RUZOMBEROK","SK","Slovakia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("SK010","ZILINA","SK","Slovakia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("SK012","KOSICE","SK","Slovakia");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK002","ABERDEEN","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK008","ALDERSHOT","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK026","BASILDON","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK031","BELFAST","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK034","BIRKENHEAD","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK038","BLACKBURN/DARWEN","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK039","BLACKPOOL","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK044","BOURNEMOUTH","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK050","BRIDGEND","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK051","BRIGHTON/WORTHING/LITTLEHAMPTON","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK052","BRISTOL","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK055","BURNLEY/NELSON","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK062","CAMBRIDGE","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK066","CARDIFF","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK070","CHELTENHAM/CHARLTON KINGS","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK073","CHESTERFIELD/STAVELEY","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK087","COVENTRY/BEDWORTH","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK089","CRAWLEY","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK095","DEARNE VALLEY","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK097","DERBY","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK098","DONCASTER","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK103","DUNDEE","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK110","EDINBURGH","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK122","GLASGOW","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK125","GLOUCESTER","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK132","LONDON","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK133","GREATER MANCHESTER","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK135","GRIMSBY/CLEETHORPES","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK143","HASTINGS/BEXHILL","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK149","HIGH WYCOMBE","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK159","IPSWICH","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK168","KINGSTON-UPON-HULL","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK173","LEICESTER","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK178","LIVERPOOL","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK184","LUTON/DUNSTABLE","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK190","MANSFIELD","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK193","MILTON KEYNES","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK200","NEWPORT","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK204","NORTHAMPTON","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK207","NORWICH","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK208","NOTTINGHAM","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK211","OXFORD","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK214","PETERBOROUGH","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK216","PLYMOUTH","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK221","PORTSMOUTH","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK223","PRESTON","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK224","READING/WOKINGHAM","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK238","SHEFFIELD","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK241","SLOUGH","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK242","SOUTHAMPTON/EASTLEIGH","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK243","SOUTHEND","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK244","SOUTHPORT/FORMBY","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK246","ST. ALBANS/HATFIELD","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK256","SUNDERLAND/WHITBURN","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK259","SWANSEA","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK260","SWINDON","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK263","TEESSIDE","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK267","THANET","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK268","THE MEDWAY TOWNS","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK269","THE POTTERIES","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK271","TORBAY","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK274","TYNESIDE","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK275","WARRINGTON","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK279","WEST MIDLANDS","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK280","WEST YORKSHIRE","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK287","WIGAN","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK301","YORK","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK319","TELFORD","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK320","Wellingborough","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK321","Tilbury","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK322","Hertford","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK323","Burton","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK324","Bedford","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK325","Fareham","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK326","Poole","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK327","Levenmouth","UK","United Kingdom");
INSERT INTO `T_BigCity` (`bigCityID`, `bigCity`, `bigCountryCode`, `CountryName`) VALUES ("UK328","Meadowhead","UK","United Kingdom");
