INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("UWWCASA","Ztype","Urban Waste Water Treatment Directive coast area Sensitive area");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("UWWCLSA","Ztype","Urban Waste Water Treatment Directive coast line Sensitive area");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("UWWCMSA","Ztype","Urban Waste Water Treatment Directive Catchment of Sensitive area defined in the sense of Article 5.5 of the UWWTD");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("UWWLKSA","Ztype","Urban Waste Water Treatment Directive lake Sensitive area");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("UWWRISA","Ztype","Urban Waste Water Treatment Directive river Sensitive area");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("UWWTDLSA","Ztype","Urban Waste Water Treatment Directive Less sensitive area");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("UWWTWSA","Ztype","Urban Waste Water Treatment Directive Transitional water Sensitive area");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("CW","WaterBodyType","discharge into coastal water");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("ES","WaterBodyType","discharge into estuary");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("FW","WaterBodyType","discharge into freshwater");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("LC","WaterBodyType","discharge on land (catchment of coastal water)");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("LF","WaterBodyType","discharge on land (catchment of freshwater and / or estuary)");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("A54","TypeOfReceivingArea","Art. 5(4) area");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("A58","TypeOfReceivingArea","Art. 5(8) area (entire Member State)");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("CSA","TypeOfReceivingArea","Catchment in the sense of Art. 5(5)");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("LSA","TypeOfReceivingArea","Less sensitive area");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("NA","TypeOfReceivingArea","Normal area");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("SA","TypeOfReceivingArea","Sensitive area");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("0","State","inactive");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("1","State","active");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("2","State","temporary inactive");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("A523","SpZTyp","Art 5.(2,3) area");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("A54","SpZTyp","Art. 5(4) area (only possible if Article 5.4 applies before or at the reference year of the report)");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("A54523","SpZTyp","Art. 5(4) and 5 (2,3) area");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("A58523","SpZTyp","Art. 5(8) and 5 (2,3) area");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("A5854","SpZTyp","Art. 5(8) and 5(4) area (entire Member State) (only possible if Article 5.4 applies before or at the reference year of the report)");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("A5854523","SpZTyp","Art. 5(8), 5(4) and 5 (2,3) area (only possible if Article 5.4 applies before or at the reference year of the report)");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("B","SewageNetwork","both combined & sepa");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("C","SewageNetwork","combined");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("S","SewageNetwork","separated");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("F","Perf","Fail");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("NA","Perf","Data not available");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("NR","Perf","Not relevant");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("P","Perf","Pass");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("aN","Parameter","Nitrogen eutrophication (nitrogen have to be removed from the Urban Waste Water Treatement plants belonging to agglomeration of more than 10 000 p.e.)");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("aP","Parameter","Phosphorus eutrophication  (nitrogen have to be removed from the Urban Waste Water Treatement plants belonging to agglomeration of more than 10 000 p.e.)");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("b","Parameter","Nitrogen drinking water (nitrogen have to be removed from the Urban Waste Water Treatement plants belonging to agglomeration of more than 10 000 p.e.)");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("c","Parameter","Areas where further treatment than that prescribed in Article 4 of the UWWTD is necessary to fulfil Council Directives");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("C","Method54","Calculated");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("E","Method54","Estimated");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("M","Method54","Measured");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("C","Method2","calculated");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("E","Method2","estimated");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("C","Method1","Calculated");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("E","Method1","Estimated");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("M","Method1","Measured");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("IN","Irrigation","Infiltration");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("IR","Irrigation","Irrigation");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("OT","Irrigation","Other");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("Agregation","EvolutionType","results from the aggregation of previously reported SA or LSA");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("ChangeBothAggregatio","EvolutionType","complex operation involving both the splitting and aggregation of previously reported SA or LSA");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("ChangeCode","EvolutionType","the identifiers used at national level have changed  (the real-world entities have not changed)");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("ChangeGeometry","EvolutionType","results from the change of the geometry of a previously reported SA or LSA");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("Deletion","EvolutionType","a SA or LSA that no longer exists and has no successor (in this case put also 'Deletion' in the rcaCode cell)");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("Other","EvolutionType","other reason");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("Splitting","EvolutionType","results from the splitting of a previously reported SA or LSA");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("AL","Country","Albania");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("AT","Country","Austria");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("BA","Country","Bosnia and Herzegovina");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("BE","Country","Belgium");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("BG","Country","Bulgaria");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("BY","Country","Belarus");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("CH","Country","Switzerland");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("CY","Country","Cyprus");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("CZ","Country","Czechia");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("DE","Country","Germany");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("DK","Country","Denmark");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("EE","Country","Estonia");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("ES","Country","Spain");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("FI","Country","Finland");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("FR","Country","France");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("GB","Country","United Kingdom");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("GE","Country","Georgia");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("GR","Country","Greece");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("HR","Country","Croatia");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("HU","Country","Hungary");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("IE","Country","Ireland");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("IS","Country","Iceland");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("IT","Country","Italy");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("LI","Country","Liechtenstein");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("LT","Country","Lithuania");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("LU","Country","Luxembourg");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("LV","Country","Latvia");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("MC","Country","Monaco");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("MD","Country","Moldova, Republic of");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("ME","Country","Montenegro");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("MK","Country","Macedonia, the Former Yugoslav Republic of");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("MT","Country","Malta");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("NL","Country","Netherlands");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("NO","Country","Norway");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("PL","Country","Poland");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("PT","Country","Portugal");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("RO","Country","Romania");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("RS","Country","Serbia");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("SE","Country","Sweden");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("SI","Country","Slovenia");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("SK","Country","Slovakia");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("SM","Country","San Marino");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("TR","Country","Turkey");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("ISCON","CollectingSystem","Collecting system is connected to UWWTP");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("NOTCON","CollectingSystem","Collecting system is not connected to UWWTP");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("ALC","Branch","Production of alcohol and alcoholic beverages");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("BREW","Branch","Breweries");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("DRINK","Branch","Manufacture and bottling of soft drinks");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("FEED","Branch","Manufacture of aninmal feed from plant products");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("FISH","Branch","Fish-processing industry");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("FRUIT","Branch","Manufacture of fruit and vegetable products");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("GELA","Branch","Manufacture of gelatine and glue from hides, skin and bones");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("MALT","Branch","Malt-houses");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("MEAT","Branch","Meat industry");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("MILK","Branch","Milk-processing");
INSERT INTO `T_LOV` (`lovKey`, `lovName`, `lovValue`) VALUES ("POTA","Branch","Potato-processing");
