INSERT INTO `T_ReceivingAreas_LSA` (`rca61DateDesignation`, `rcaAbsenceRisk`, `rcaBeginLife`, `rcaCode`, `rcaEndLife`, `rcaEnvDom`, `rcaHydraulic`, `rcaHydrology`, `rcaHyperlink`, `rcalsaRemarks`, `rcaMorphology`, `rcaName`, `rcaZtype`, `ReceivingAreas_LSAId`, `repCode`) VALUES ("07/13/15 00:00:00","1","07/14/15 00:00:00","PTLS01A",NULL,"WATER",1,1,NULL,"National legal act on designation/review of receiving areas (LSA): Decreto-Lei n.º 133/2015 de 13 de julho",1,"Cabo da Roca/Estoril","UWWTDLSA",88966,"PT_2018");
INSERT INTO `T_ReceivingAreas_LSA` (`rca61DateDesignation`, `rcaAbsenceRisk`, `rcaBeginLife`, `rcaCode`, `rcaEndLife`, `rcaEnvDom`, `rcaHydraulic`, `rcaHydrology`, `rcaHyperlink`, `rcalsaRemarks`, `rcaMorphology`, `rcaName`, `rcaZtype`, `ReceivingAreas_LSAId`, `repCode`) VALUES ("07/13/15 00:00:00","1","07/14/15 00:00:00","PTLS08A",NULL,"WATER",1,1,NULL,"National legal act on designation/review of receiving areas (LSA): Decreto-Lei n.º 133/2015 de 13 de julho",1,"Ilha da Madeira","UWWTDLSA",88967,"PT_2018");
INSERT INTO `T_ReceivingAreas_LSA` (`rca61DateDesignation`, `rcaAbsenceRisk`, `rcaBeginLife`, `rcaCode`, `rcaEndLife`, `rcaEnvDom`, `rcaHydraulic`, `rcaHydrology`, `rcaHyperlink`, `rcalsaRemarks`, `rcaMorphology`, `rcaName`, `rcaZtype`, `ReceivingAreas_LSAId`, `repCode`) VALUES ("10/01/97 00:00:00","1",NULL,"ISLS001",NULL,"WATER",0,0,NULL,NULL,0,"Faxafloi (Capital aerea) vidtaki","UWWTDLSA",88975,"IS2018");
INSERT INTO `T_ReceivingAreas_LSA` (`rca61DateDesignation`, `rcaAbsenceRisk`, `rcaBeginLife`, `rcaCode`, `rcaEndLife`, `rcaEnvDom`, `rcaHydraulic`, `rcaHydrology`, `rcaHyperlink`, `rcalsaRemarks`, `rcaMorphology`, `rcaName`, `rcaZtype`, `ReceivingAreas_LSAId`, `repCode`) VALUES ("12/27/94 00:00:00","1",NULL,"ISLS003",NULL,"WATER",0,0,NULL,"The less sensitive area is beging delineated",0,"Hafnarfjordur vidtaki","UWWTDLSA",88976,"IS2018");
INSERT INTO `T_ReceivingAreas_LSA` (`rca61DateDesignation`, `rcaAbsenceRisk`, `rcaBeginLife`, `rcaCode`, `rcaEndLife`, `rcaEnvDom`, `rcaHydraulic`, `rcaHydrology`, `rcaHyperlink`, `rcalsaRemarks`, `rcaMorphology`, `rcaName`, `rcaZtype`, `ReceivingAreas_LSAId`, `repCode`) VALUES ("12/19/09 00:00:00","1",NULL,"ISLS008",NULL,"WATER",0,0,NULL,NULL,0,"Akranes vidtaki","UWWTDLSA",88977,"IS2018");
INSERT INTO `T_ReceivingAreas_LSA` (`rca61DateDesignation`, `rcaAbsenceRisk`, `rcaBeginLife`, `rcaCode`, `rcaEndLife`, `rcaEnvDom`, `rcaHydraulic`, `rcaHydrology`, `rcaHyperlink`, `rcalsaRemarks`, `rcaMorphology`, `rcaName`, `rcaZtype`, `ReceivingAreas_LSAId`, `repCode`) VALUES ("09/26/15 00:00:00","1",NULL,"ISLS002",NULL,"WATER",0,0,NULL,NULL,0,"Akureyri, innri Eyjafjordur vidtaki","UWWTDLSA",88978,"IS2018");
INSERT INTO `T_ReceivingAreas_LSA` (`rca61DateDesignation`, `rcaAbsenceRisk`, `rcaBeginLife`, `rcaCode`, `rcaEndLife`, `rcaEnvDom`, `rcaHydraulic`, `rcaHydrology`, `rcaHyperlink`, `rcalsaRemarks`, `rcaMorphology`, `rcaName`, `rcaZtype`, `ReceivingAreas_LSAId`, `repCode`) VALUES ("01/28/05 00:00:00","1",NULL,"ISLS014",NULL,"WATER",0,0,NULL,NULL,0,"Dalvik, vidtaki","UWWTDLSA",88979,"IS2018");
INSERT INTO `T_ReceivingAreas_LSA` (`rca61DateDesignation`, `rcaAbsenceRisk`, `rcaBeginLife`, `rcaCode`, `rcaEndLife`, `rcaEnvDom`, `rcaHydraulic`, `rcaHydrology`, `rcaHyperlink`, `rcalsaRemarks`, `rcaMorphology`, `rcaName`, `rcaZtype`, `ReceivingAreas_LSAId`, `repCode`) VALUES ("05/17/94 00:00:00","1",NULL,"ISLS017",NULL,"WATER",0,0,NULL,NULL,0,"Husavik, Skjalfandafloi vidtaki","UWWTDLSA",88980,"IS2018");
INSERT INTO `T_ReceivingAreas_LSA` (`rca61DateDesignation`, `rcaAbsenceRisk`, `rcaBeginLife`, `rcaCode`, `rcaEndLife`, `rcaEnvDom`, `rcaHydraulic`, `rcaHydrology`, `rcaHyperlink`, `rcalsaRemarks`, `rcaMorphology`, `rcaName`, `rcaZtype`, `ReceivingAreas_LSAId`, `repCode`) VALUES ("12/15/05 00:00:00","1","02/13/08 00:00:00","NORCA16",NULL,"WATER",0,1,NULL,NULL,1,"Kystlinje Lindesnes - Grense Jakobselv","UWWTDLSA",88982,"NO_UWWTD_2018");
